### ISSUE TITLE
Include dashheader.erb in main.erb

### ISSUE THREAD

**Issue by GGGav** [Smashing/smashing#101]
I have several dashboards which have the same top rows and then differ in the rest of their content.  To save duplicating the top chuck of each dashboard I would like to be able to include a standard .erb file in the top of each dashboard file.
I have tried this....

```
<div class="gridster">
  <ul>
      <%= erb :header %>
      <!-- now the widgets specific to this dashboard -->
      <li data-row="2" data-col="5" data-sizex="1" data-sizey="3">
      <div data-id="spacer1" data-view="Mistext"></div>
    </li>
    <!-- etc.  -->
 </ul>
</div>
```

With the file 'header.erb' in the dashboards directory.
This renders but gets the position of the widgets wrong.
Is there a better way to attempt this?

**Comment by tylermauthe** [comment]
Hello! Thanks for your interest in using Smashing. Unfortunately, the bandwidth available to support issues is greatly exceeded by the number of issues reported.

Due to this limitation, the maintainers of Smashing do not answer support requests submitted as GitHub issues. This is stated in the [CONTRIBUTING.d](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue), please read that for more details.

Thanks!
