### ISSUE TITLE
Nested Widgets?

### ISSUE THREAD

**Issue by robbykim** [Smashing/smashing#108]
Is this possible?

I have a graph widget that I want to use multiple times so I have something like:

`dash.erb`

    <div class="widget-A" data-view="Example" data-id="widget-A"></div> 
    <div class="widget-B" data-view="Example" data-id="widget-B"></div> 

`in my widget's example.html`

    <div class="graph" data-view="Graph" data-id="ping" />

Is there any way to feed different data into the graph widget's `onData` method through the parent id to differentiate? For example: `send_event('widget-A', 'ping')`? I can't seem to find anything on nested widgets or reusing widgets like this.

**Comment by tylermauthe** [comment]
Hello! Thanks for your interest in using Smashing. Unfortunately, the bandwidth available to support issues is greatly exceeded by the number of issues reported.

Due to this limitation, the maintainers of Smashing do not answer support requests submitted as GitHub issues. This is stated in the [CONTRIBUTING.d](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue), please read that for more details.

Thanks!
