### ISSUE TITLE
Migrate to another platform (Gitlab or another) to keep things moving

### ISSUE THREAD

**Issue by julian-alarcon** [Smashing/smashing#109]
Hi!

You should consider the migration to another platform after the MS announcement of the acquisition of GitHub.
http://www.itprotoday.com/open-source/why-open-source-software-moving-gitlab-after-microsoft-github-deal
https://www.bleepingcomputer.com/news/technology/gitlab-sees-huge-traffic-spike-after-news-of-microsoft-buying-github/
https://dev.to/maxart2501/what-i-think-is-bad-about-microsoft-acquiring-github-gme
https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/
https://blog.github.com/2018-06-04-github-microsoft/

**Comment by kinow** [comment]
I'm neutral for that. Before the MS announcement, it was a private company, not a foundation, trust, not for profit, etc. I prefer to focus the time/effort on the missing bugs, and keep an eye on what happens. If the worst happen, moving to alternatives like GitLab, BitBucket, an etc, are fairly simple.

Feel free to reach at Gitter if you would like to discuss that. We aim at leaving GitHub issues only for bugs and enhancements in the code, due to the limited developer bandwidth.
