### ISSUE TITLE
Events not reaching dashboard on Ubuntu

### ISSUE THREAD

**Issue by steve-giffgaff** [Smashing/smashing#112]
My smashing dashboard works fine on my Mac, but when I run on an EC2 instance running Ubuntu 16.04, the events don't update the dashboard until I exit the dashboard. I read somewhere to try

> rackup -p 3030 -s webrick

...but no luck. Any ideas?

**Comment by tylermauthe** [comment]
Hello! Thanks for your interest in using Smashing. Unfortunately, the bandwidth available to support issues is greatly exceeded by the number of issues reported.

Due to this limitation, the maintainers of Smashing do not answer support requests submitted as GitHub issues. This is stated in the [CONTRIBUTING.d](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue), please read that for more details.

Thanks!

**Comment by tylermauthe** [comment]
PS: it could be a million things - sounds like a load balancer issue or reverse proxy issue to me.

**Comment by olepg** [comment]
I realize this is an old thread, but it might help people coming from google later.

I had the same issue, and seem to have found a workaround:
You need to run the server through PUMA, instead of Thin

gem install puma
puma config.ru -p 3030
