### ISSUE TITLE
Can you dynamically change text outside of a Widget ?

### ISSUE THREAD

**Issue by prynhart** [Smashing/smashing#113]
Just getting started with Smashing so apologies for the basic question and also submitting this as an issue.  But I was wondering whether there is anyway to dynamically (i.e. via a curl request or similar) change text which is outside of a widget altogether ?  For example, in the screenshot below, I'd like to be able to change "Hello World!" (also highlighted by the red box) to something else:

<img width="1257" alt="helloworld" src="https://user-images.githubusercontent.com/15762315/42188528-5407f8ea-7ea8-11e8-992a-181741436e41.png">

With Thanks in advance,

Patrick

**Comment by kinow** [comment]
Hello! Thanks for your interest in using Smashing. Unfortunately, the bandwidth available to support issues is greatly exceeded by the number of issues reported.

Due to this limitation, the maintainers of Smashing do not answer support requests submitted as GitHub issues. This is stated in the [CONTRIBUTING.md](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue), please read that for more details.

Thanks!

**Comment by prynhart** [comment]
Apologies!  Wasn't sure where to ask questions.  Thanks for the link
