### ISSUE TITLE
Smashing insists on loading Rack 1.5.5; but can't parse config.ru with it on Ruby 2.5.x

### ISSUE THREAD

**Issue by unquietwiki** [Smashing/smashing#114]
```
2018/07/21 01:59:49 [error] 4139#4139 Ruby: Failed to run ruby script
2018/07/21 01:59:49 [error] 4139#4139 Ruby: /var/lib/gems/2.5.0/gems/rack-1.5.5/lib/rack/urlmap.rb:62:in `block in call': undefined method `+' for nil:NilClass (NoMethodError)
2018/07/21 01:59:49 [error] 4139#4139 from /var/lib/gems/2.5.0/gems/rack-1.5.5/lib/rack/urlmap.rb:50:in `each'
2018/07/21 01:59:49 [error] 4139#4139 from /var/lib/gems/2.5.0/gems/rack-1.5.5/lib/rack/urlmap.rb:50:in `call'
```

**Comment by tylermauthe** [comment]
If you're asking that we support ruby 2.5.x - that's reasonable, and I'm sorry that I closed it. However - you didn't make that very clear in your original issue.

Before you create your first issue in this repo, you're prompted to read the CONTRIBUTING.md - which outlines the steps for getting support:
https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue

I know that you didn't follow that protocol and your issue was a one sentence description in the title with a pasted output from your terminal - as such I think I'm still okay with my decision to close without explanation... but I'm still open to discussing upgrading to Ruby 2.5.x now that you've made it clearer that's what you're asking for.

Yes, we happily accept PRs - also outlined in the CONTRIBUTING.md:
https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#pull-requests

I'm happy to make this change, so long as this isn't going to be a breaking change for our entire userbase. That will drastically increase the number of times I have to close tickets with a canned response linking to the wiki page. Thank you for your time.

**Comment by unquietwiki** [comment]
@tylermauthe Thank you for looking into this. I apologize for not being more clear with the description; I blame lack of sleep the past week on that. What prompted all of this to begin with, is that I'm trying to migrate a dashboard from a 16.04 self-hosted VM another co-worker has made; to an 18.04 system on a more permanent host. I found it curious that the project was deliberately using an older version of Rack; and wanted to bring it to your attention, since it seems to be incompatible with the newer OS & Ruby. I also wholly agree on not wanting to make undue demands on your time via help requests: been in support roles too long myself! 👍

**Comment by tylermauthe** [comment]
Are you using version 1.1.0? https://rubygems.org/gems/smashing/versions/1.1.0

**Comment by tylermauthe** [comment]
Also - you could use chruby to change the ruby version on the system:
https://github.com/postmodern/chruby

**Comment by unquietwiki** [comment]
@tylermauthe Yeah it was 1.1.0. Also had tried a gem update too. And that chruby looks useful: thanks for the tip.

**Comment by tylermauthe** [comment]
I am also wondering if you have a system version of rack installed that's a different version...

Try using bundler's deployment options - you might not even need chruby:
https://bundler.io/v1.6/deploying.html

**Comment by unquietwiki** [comment]
@tylermauthe Cool suggestions. I'll report back on Monday; the system in question is back at the office. Thank you again for investigating this btw.

**Comment by unquietwiki** [comment]
Hey @tylermauthe . Well, I dug into this, and got things kind of working.  So migrating my user's dashboard from Ubuntu 16.04 to 18.04; I stripped out the original attempt to install Ruby gems for this, and did a bunch of digging online. Here's what I came up with so far: his CoffeeScript still doesn't seem to be firing off properly, but that could be something in how the dashboard is setup.

'''
sudo apt install ruby-coffee-script coffeescript -y
sudo gem install bundler
cd (directory for dashboard)
rm -fr vendor
bundle package --all
bundle install --no-deployment --path vendor/bundle
bundle lock --update
bundle update
bundle clean
bundle package --all

bundle exec smashing start
'''

**Comment by unquietwiki** [comment]
Okay, seems like things are verified working on our end; we ran into some manifestation of #31 on Edge, but Firefox & Chrome are good. I have the software running in a systemd script; running it via https://unit.nginx.org/ doesn't seem to work well, since specifying the Ruby gem directories for this are a problem.
