### ISSUE TITLE
Widgets width

### ISSUE THREAD

**Issue by Lavrih** [Smashing/smashing#133]
Hi

How could i set the width of top 2 widgets to 50% and the middle one to 100%. Can i do it in widgets or is it set in assets/stylesheets ?
![image](https://user-images.githubusercontent.com/39552769/57221730-824e6f00-7000-11e9-85c5-5a065d809f08.png)

**Comment by kinow** [comment]
Hello! Thanks for your interest in using Smashing. Unfortunately, the bandwidth available to support issues is greatly exceeded by the number of issues reported.

Due to this limitation, the maintainers of Smashing do not answer support requests submitted as GitHub issues. This is stated in the [CONTRIBUTING.d](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue), please read that for more details.

Thanks!
