### ISSUE TITLE
Graph widget x lables

### ISSUE THREAD

**Issue by LuxoftAKutsan** [Smashing/smashing#146]
Is there any ability to setup x lables manually? 
Current ’XXs’ is completely not obvious.
Or should I use another custom widget if I need to see x lables?

**Comment by kinow** [comment]
Hello! Thanks for your interest in using Smashing. Unfortunately, the bandwidth available to support issues is greatly exceeded by the number of issues reported.

Due to this limitation, the maintainers of Smashing do not answer support requests submitted as GitHub issues. This is stated in the [CONTRIBUTING.d](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue), please read that for more details.

Thanks!
