### ISSUE TITLE
Installing on Raspi buster 

### ISSUE THREAD

**Issue by Dave-DigiMim** [Smashing/smashing#167]
sudo apt-get install ruby2.3-dev
this was successful
but this was not
pi@raspberrypi:~/Cellar $ sudo gem install smashing
Building native extensions. This could take a while...
ERROR:  Error installing smashing:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/eventmachine-1.2.7/ext
/usr/bin/ruby2.5 -r ./siteconf20200621-23957-f66zcs.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/eventmachine-1.2.7 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/arm-linux/2.5.0/eventmachine-1.2.7/gem_make.out
I see that although ruby2.3 was installed it seems to have installed Gems 2.5

**Comment by kinow** [comment]
Hi @Dave-DigiMim 

Have you looked at older issues here? I remember seeing a few ones about issues with Raspberry and Smashing before, e.g. https://github.com/Smashing/smashing/issues/78

Bruno

**Comment by rompic** [comment]
why do you want to install such an old ruby version?

**Comment by jerdog** [comment]
FWIW - I had the same issue on a full, new install in an Ubuntu 18.04 LTS Azure instance. I first had to:

```
sudo snap install --classic ruby
sudo apt install build-essential
sudo gem install smashing
```

then it worked

**Comment by kinow** [comment]
Added the workaround above to our installation Wiki. I'm working to update the Ubuntu LTS installation, and the CentOS installation instructions. Unfortunately we don't have bandwidth to maintain the installation instructions for many distros, nor for older versions. But documenting the installation problems in our Wiki might at least help users to find everything in a single place instead of having to search issues/PR's.

https://github.com/Smashing/smashing/wiki/Installation#troubleshooting

Thanks!
