### ISSUE TITLE
Dashing Fork

### ISSUE THREAD

**Issue by MartynKeigher** [Smashing/smashing#30]
Evening!

Went to check the network graph to see what other peeps have done to the smashing fork SINCE Shopify announced that project would be discontinued (from a support PoV), but i cannot as there are 'Too Many forks to show' - given the popularity Dashing had (and what Smashing will have!).

Is there an intent at all to 're-submit this project' as a new project (not forked from anything) so that we can track each others edits/pulls/forks from the project as we know as 'Smashing' from this point forward??

FWIW: I learned so much coding skills from browsing peoples forks etc... I love to see what other people are doing not only with the project, but this for me is a learning tool for sure!!

I have many years experience with Dashing too - and after a re-birth of interest in this project from my employer - i'm gonna be pretty active in 'Smashing' over the coming months/year.

Consider me smashed/dashed/in the club.. whatever ya wanna call it!? ;p 

and lastly... Merry Christmas, or Happy Hanukkah, to you!

**Comment by kinow** [comment]
Morning from here @MartynKeigher! I think that sounds like a good idea. Happy to re-submit, let's just wait and see what others in the @Smashing/contributors team think about it.

 >FWIW: I learned so much coding skills from browsing peoples forks etc... I love to see what other people are doing not only with the project, but this for me is a learning tool for sure!!
>
>I have many years experience with Dashing too - and after a re-birth of interest in this project from my employer - i'm gonna be pretty active in 'Smashing' over the coming months/year.
>
>Consider me smashed/dashed/in the club.. whatever ya wanna call it!? ;p

I'm also smashed/dashed, though my primary programming languages are Java, PHP, and Python. So far I've tried to help replying issues, helping people troubleshoot, fixing smaller issues, and so it goes.

But having more people onboard, specially with experience building dashboards, widgets, and maybe industry Ruby experience, would definitely help to get the project changes happening faster.

**Comment by tylermauthe** [comment]
Hey there! Great to see ya again, happy holidays to you too sir.

I like the idea of re-submitting to clear up the network graph. I wonder what the cleanest way of doing that is...

**Comment by MartynKeigher** [comment]
Good to see you again too Tyler!! :) Long time no commit! ;p  (sad. very SAD github joke!) LMAO.
Hope you and the family had an awesome Christmas!! 

So.. IF this "smashing" is gonna be the 'official' "after-dashing", then i think it would be best for one of the admins to just either...
1) Disassociate this project from the project they forked from. - May or may not be an option in the project settings. (May need GitHub support to intervene)
2) Take a big leap of faith with their community and just delete the repo and start over. (A mailing list to inform those not aware of the change, as this will refresh everything) - esp. the issues. If they want to take this approach, then the sooner the better - so not to lose more and more data!

PS: LongTime.NoCommit. (I think i need that on a T-shirt! ;p)

**Comment by MartynKeigher** [comment]
I have just stumbled across this service....

http://forked.yannick.io/smashing/smashing

It's not _exactly_ what im after at all, but if I want to spend time on it, then i guess it _might_ be semi-useful. I want the graphs. I'm sure im not the only person who thinks GitHub's Network Graph approach is flawed.

I think some good steps for Smashing to take would be consolidate the best things that different people did over the years with Dashing and incorporate those into the ONE product.
I merged many things that the community did with 'their dashing' and put them in mine. Some were in the app (eg: FontAwesome update & widget creation) and some were more OS/ruby based as a whole (eg: running on PUMA webserver, instead of thin, and updating dashing to work on recent version of ruby and not 1.9.3)

I know several ppl still running this on Ruby 1.9.3 just so dashing will work. Currently... the smashing install fails on ruby 1.9.3 and some people don't know ruby well enough to update it. - and therefore forget using dashing/smashing and go elsewhere. (mainly grafana these days) and we need to change that. I'm down for doing the documentation... I just need to know if their is a serious interest from the team here of the wanting to do this. 'dashing rebirth' or not.

Is there another fork of dashing that is more committed than smashing? Not trying to stir a pot here, but the last thing I wanna see/read about this fork is: "Smashing: Yet Another half-assed dashing fork!"

I'm all in. Just need to make sure some one, or others, is in it to win it too!

**Comment by tylermauthe** [comment]
Looks like we have to contact support to switch it:
http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

I've sent in a request to have this link severed.

Regarding your other input, it is much appreciated. Every pot needs a good stirring now and then!

I'd definitely like to get some of the smaller breaking changes, like Font Awesome and Rufus updates, merged into the mainline.

Regarding the Operational aspects of Smashing (IE: how to get it running and ensure reliability on various OS's), I'd like to provide more assistance in this realm for sure. We get a TON of support requests around this any they make me sad.

Some suggestions for this:
- Laziest: Better Install docs for Ubuntu 14.04 & 16.04 and CentOS 6 & 7
- A proper init script.
- Proper Debian and Yum packages
- An Official Docker container would also be great

Regarding Puma, I don't know if you recall all the issues that surrounded the SSE problems with Sinatra and Puma (sinatra#1035). The dashboard appears to work, but there are a ton of front-end errors because the SSE doesn't remain connected as Puma kills the socket. There's a good writeup of how Rails made this work here if you're curious: http://tenderlovemaking.com/2012/07/30/is-it-live.html

We do have a Puma fork of Smashing here, but I'm not overly confident in the implementation - it was basically a nasty mutex-fueled hack to simulate EventMachine: https://github.com/Smashing/smashing/tree/puma_webserver

I have a bunch of other ideas outlined here also:
https://github.com/Smashing/smashing/issues/8#issuecomment-240203263

I've also had a few other ideas as I've been assisting someone with implementing Dashing at work. It might be nice to consolidate all the future project ideas somewhere. It feels like there may be quite a few of them floating around in our heads right now. I'm going to create individual tickets for each of the ideas that I have and tag them with `enhancement`.

**Comment by tylermauthe** [comment]
GitHub has de-forked us. Closing issue!

**Comment by MartynKeigher** [comment]
Awesome!! 

Thanks Tyler and Happy New Year to you and your family!! :) 

PS: May the Smashing 'forking' begin!!_...or at least the viewing of it!_ ;p

**Comment by tylermauthe** [comment]
No worries and Happy New Year to you also! Does the Network Graph look any better to you? Not sure that the un-forking fixed anything...

**Comment by MartynKeigher** [comment]
Well previously, it wouldnt show anything, as there was 'too much to show', so by un-forking it from Dashing, I can now see the individual forks of 'Smashing' itself. 

I'm spinning up a Linux VM now, then i'll fork this project and install my 'forks master' on the VM. 

More to follow....  :) 

(On a separate note.. it may be worth you or @kinow to create the gitter channel, as that way you can tie the gitter directly to this repo. If you do that then you can do some cool integration between the 2.) :)
