### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by d-zalewski** [Smashing/smashing#31]
Any chances we get the IE fix merge https://github.com/Shopify/dashing/pull/310 ?

Thanks

Dom

**Comment by MartynKeigher** [comment]
This fork may be of interest to you...

https://github.com/brightfunds/dashing/commit/60b14006be461b0402de0931366812d0d69eff47

**Comment by tylermauthe** [comment]
@d-zalewski - I'd like to know a bit more about your use case. What version of IE / Edge are you looking to support?

I am leery of that PR (despite my comment 1.5 yrs ago) because it lacks the refinement of a well formed contribution and uses a Polyfill. There are also more recent comments regarding it's lack of Edge support.

**Comment by d-zalewski** [comment]
IE11 and Edge ideally

**Comment by christianhau** [comment]
Hi! my smashing dashboard is not showing in both IE11 and Edge, all that is showing is 
![capture](https://user-images.githubusercontent.com/719236/31736173-5130103c-b444-11e7-9b8c-ef5f59ef1499.PNG)

Anyone know of a fix to this?
