### ISSUE TITLE
Switch multiple dashboard via JS Swiper

### ISSUE THREAD

**Issue by 1ucay** [Smashing/smashing#55]
Hi, it would be possible to create multiple dasboards screens via Swiper?

http://idangero.us/swiper/

**Comment by PGeffriaud** [comment]
Hi,

Have you succeeded to integrate Smashing with JS Swiper ?

On my side, I tried to add [Bootstrap Carousel](https://v4-alpha.getbootstrap.com/components/carousel/#with-indicators) in order to rotate over multiple dashboards as you wanted to do.
But I failed because Smashing is made in order to load one dashboard at a time and there is one different URL per dashboard. On the contrary, Bootstrap Carousel needs to load each frames on the same page.

I am also interested if you have any clues or solutions to bring here.

**Comment by caitfriedlander** [comment]
Have there been any developments on this? I'm trying to do this as well.
