### ISSUE TITLE
Provide a way to log to system logs

### ISSUE THREAD

**Issue by kinow** [Smashing/smashing#66]
This is a current request I got from a co-worker (system administrator). At the moment some of the jobs in our dashboard are - as I've normally done - using `puts` to log a few debug messages.

Recently we had a problem with some dataset, and I told him how I found the issue running it locally and looking at the logs. He asked me to output these messages to the system (Red Hat Linux 6) logs.

This issue is to provide users with similar problems, a way to choose on how to output to stdout, stderr, system log, etc.

**Comment by tylermauthe** [comment]
As an Operations person myself, I disagree with this wholeheartedly. Unix already provides plenty of facilities for redirecting streams - best practice in 12 factor apps is to log to stdout and let the environment handle it:
https://12factor.net/logs

If you aren't running in Docker, k8s or Heroku then you can just use good ol' unix redirects, pipes and rsyslog's logger. The real problem is that we need to make some damn good RPM and Yum packages, that include things like init script for each OS.

If I write an init script for RHEL 6, would you be able to test it out for me? We can use that as the basis for the RPM package issue also.

**Comment by kinow** [comment]
I think we both agree :-)

I'm not going to look at Ruby gems, or modifying much/any code. My initial guess is that I can find a good way to do that with just stream redirection. The problem is that when he asked me how to do that for the dashboards, I didn't have anything ready for him, nor any documentation. 

>If I write an init script for RHEL 6, would you be able to test it out for me?

You can target CentOS or RHEL 6/7, and I can definitely test it.

>We can use that as the basis for the RPM package issue also.

+1 as well

**Comment by kinow** [comment]
ps. I also look at the 12factor when I need to write something about software configuration, but I'll admit I never looked at the logs section. Reading it tonight :-) thanks for the pointer
