### ISSUE TITLE
the repository name

### ISSUE THREAD

**Issue by ozbillwang** [Smashing/smashing#73]
Thanks to continuing the closed project (dashing). 

I understand you'd like to have a new name for this cool project, but "smashing" is a really bad name  (mostly it is negative) and no link to its function

Can you change it back to `dashing` or directly call it `dashboard`? 

Another benefit,  we can easily search it from google as well. With the current name `smashing`, it is no result in google search with keyword `github dashboard`

**Comment by tylermauthe** [comment]
Thanks for your input! We changed the name because we intend to introduce breaking changes to the core code base. These breaking changes are desperately needed as many dependencies of this project are outdated, unsupported (and breaking), and unperformant. Basically the whole project needs a facelift, so we called is Smashing (the spiritual successor to Dashing).

That being said, the name change was probably a bit hasty - because I haven't made any breaking changes.
