### ISSUE TITLE
must leave cli window open

### ISSUE THREAD

**Issue by daven1985** [Smashing/smashing#76]
Morning,

I am new to smashing, but I find it I close my CLI window it will no longer reload... and I Have to keep up the status screen showing when people have loaded my dashboard, am I doing something wrong?

**Comment by kinow** [comment]
Afternoon,

Do you mean the command line? The terminal window where you started your smashing dashboard?

If so, it is the expected behaviour. If you are on  Linux (maybe Mac too?) then you need to install a service to run smashing for you in the background - https://github.com/Smashing/smashing/wiki/Init.d-script

If you are on Windows, you can do similarly (see https://docs.microsoft.com/en-us/dotnet/framework/windows-services/introduction-to-windows-service-applications for some intro on that).

Hope that helps
Bruno

**Comment by kinow** [comment]
Closing as it doesn't look like a bug. But feel free to reply here @daven1985 In case it's actually a bug, we can reopen it later.
